### ISSUE TITLE
Fin du design de la page event et inscription event

### ISSUE THREAD

**Issue by mmarchois** [marinebrnn/jeunot#53]

**Comment by florimondmanca** [comment]
@mmarchois Voilà un batch : #74 

Ça me semble mergeable en l'état

TODOs restants que j'ai identifiés

* Section "Autres événements à venir"
* Section "Pourquoi Jeunot ?" (doit pouvoir se reprendre de la page d'accueil)
* Intégration des pages d'inscription à l'événement et confirmation d'inscription (styles bruts pour l'instant)
* Confirmation sur "Annuler mon inscription", cf #57
