### ISSUE TITLE
Retours Anne F.

### ISSUE THREAD

**Issue by mmarchois** [marinebrnn/jeunot#80]
Home page : 
- [x] lien création de compte #81 
- [ ] survol sur les boutons et liens

Page de création de compte : 
- Pouvoir afficher son mot de passe

Page de mot de passe oublié : 
- Pouvoir afficher son mot de passe

Page de création de compte :
- Pouvoir afficher son mot de passe
- Typo sur "Comment vous nous avez connus ?" => connu

Page profil : 
- Rajouter mention champs obligatoire
- Ne le sont pas (à propos de moi, photo, age, genre)
- Illustration à fournir par Anne

Page article : 
- Date en anglais

Page event : 
- CTA création de compte en mode non connecté

**Comment by florimondmanca** [comment]
Survol boutons et liens :

* Dans le footer :
  - Colonne "Jeunot" et "Mentions légales etc" : souligner
  - Bouton "Se connecter" : mettre en jaune plein

**Comment by florimondmanca** [comment]
Idées outils taille des images:

* https://tinypng.com
* https://www.resizepixel.com/fr
